### ISSUE TITLE
This should be "toast-clear" instead of "toast-clean" I believe?

### ISSUE THREAD

**Issue by kevinmims** [k90mirzaei/vue-toast#1]
https://github.com/k90mirzaei/vue-toast/blob/5e84c7843cf8dae9f4ccdbfb1d9f531a695c369e/src/toast.vue#L74

This should be "toast-clear" instead of "toast-clean" I believe?

**Comment by kazemmdev** [comment]
Thanks, @kevinmims! but does it really an issue
